<a href="https://colab.research.google.com/github/rabbi303/Python_Assignments/blob/main/rabbi_ds_assignment__KNN_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('/content/sample_data/weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [5]:
df1= df.copy()
df2= df.copy()
df3= df.copy()
df4= df.copy()

In [6]:
#df2= df.drop('Gender', axis= 1)
#df2.head()

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
for col in df1.columns:
  if df1[col].dtype == np.number:
    continue
  else:
    df1[col] = le.fit_transform(df1[[col]])

<ipython-input-8-569c72e2923b>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df1[col].dtype == np.number:
/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
df1.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [10]:
x = df1.drop('Weight', axis= 1)
y = df1[['Weight']]

In [11]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [12]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [13]:
from sklearn.model_selection import train_test_split


In [14]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.30, random_state=1)

In [15]:
xtest.head()

Gender     Height
7154       0  65.068038
3258       1  70.824643
2188       1  68.663594
5609       0  65.987610
3186       1  70.901461

In [16]:
ytrain.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [17]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression() #create an object for regression

In [18]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [19]:
reg.predict([[0,65.068038]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[143.83013621]])

In [20]:
reg.score(xtrain, ytrain) #training accuracy

0.8972135459668117

In [33]:
reg.score(xtest, ytest) #test accuracy

0.905995960709116

In [21]:
from sklearn.metrics import mean_squared_error

In [22]:
# actual - predicted
mean_squared_error(ytest, reg.predict(xtest))

99.67250998070033

# KNN with Distance

In [25]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

In [26]:
knn = KNeighborsRegressor(n_neighbors= 100, weights= 'distance')

In [27]:
knn.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=100, weights='distance')

In [ ]:
pred = knn.predict(xtest)

In [31]:
pred

array([[147.31970293],
       [197.69135175],
       [182.7188573 ],
       ...,
       [159.11029304],
       [184.29795044],
       [201.38616438]])

In [38]:
r2_score(ytest, pred) #training accuracy)

0.8870187575183935

In [39]:
mean_squared_error(ytest, pred)

119.79404399882942

# KNeighborsClassifier

In [40]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
neigh = KNeighborsClassifier(n_neighbors=100)

In [46]:
for col in df2.columns:
  if df2[col].dtype == np.number:
    continue
  else:
    df2[col] = le.fit_transform(df2[[col]])

<ipython-input-46-57ca5815d572>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df2[col].dtype == np.number:
/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:
x = df2.drop('Gender', axis= 1)
y = df2[['Gender']]

In [50]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.30, random_state=1)

In [51]:
neigh.fit(xtrain,ytrain)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=100)

In [55]:
pred2 = neigh.predict(xtest)

In [56]:
pred2

array([1, 1, 1, ..., 0, 1, 1])

In [57]:
r2_score(ytest, pred2) #training accuracy)

0.6636682213696432

In [58]:
mean_squared_error(ytest, pred2)

0.08141799766264121